/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.datatokocontroller;
import javax.swing.JRadioButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.*;


/**
 *
 * @author Lab Informatika
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    datatokocontroller dc;
    public MainView() {
        initComponents();
        dc = new datatokocontroller(this);
        dc.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxcicilan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxbarang = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDatatoko = new javax.swing.JTable();
        jTxtselectednama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cicilan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        getContentPane().add(jTxtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));

        jLabel2.setText("TOKO BELA NEGARA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel3.setText("Nama Customer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBoxcicilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "6", "12" }));
        getContentPane().add(jComboBoxcicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, -1));

        jLabel4.setText("Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jComboBoxbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV", "Kulkas", "Mesin Cuci" }));
        getContentPane().add(jComboBoxbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        tabelDatatoko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDatatoko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDatatokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDatatoko);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 700, -1));

        jTxtselectednama.setEditable(false);
        getContentPane().add(jTxtselectednama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        setSize(new java.awt.Dimension(1086, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDatatokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDatatokoMouseClicked
        // TODO add your handling code here:
        int baris = tabelDatatoko.getSelectedRow();
        jTxtnama.setText(tabelDatatoko.getValueAt(baris, 0).toString());
        jComboBoxbarang.setSelectedItem(tabelDatatoko.getValueAt(baris,1).toString());
        jComboBoxcicilan.setSelectedItem(tabelDatatoko.getValueAt(baris,3).toString());
        jTxtselectednama.setText(tabelDatatoko.getValueAt(baris, 0).toString());
    }//GEN-LAST:event_tabelDatatokoMouseClicked

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(!validasiInput()){
            return;
        }
        try{
            dc.insert();
            JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan!");
            resetForm();
            dc.isitabel();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data: !" + ex.getMessage());
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(!validasiInput()){
            return;
        }
        try{
            dc.update();
            JOptionPane.showMessageDialog(this, "Data Berhasil diubah!");
            resetForm();
            dc.isitabel();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Gagal Mengubah Data: !" + ex.getMessage());
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            dc.delete();
            JOptionPane.showMessageDialog(this, "Data Berhasil dihapus!");
            resetForm();
            dc.isitabel();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Gagal Menghapus Data:" + ex.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void resetForm(){
        jTxtnama.setText("");
        jComboBoxbarang.setSelectedItem("TV");
        jComboBoxcicilan.setSelectedItem("3");
    }
    
    private boolean validasiInput(){
//        try{
            if(jTxtnama.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Semua field harus diisi.");
                return false;
            }
            return true;
//        } catch()
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> jComboBoxbarang;
    private javax.swing.JComboBox<String> jComboBoxcicilan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtnama;
    private javax.swing.JTextField jTxtselectednama;
    private javax.swing.JTable tabelDatatoko;
    // End of variables declaration//GEN-END:variables

    public JTable getTabelDatatoko() {
        return tabelDatatoko;
    }

    public void setTabelDatatoko(JTable tabelDatatoko) {
        this.tabelDatatoko = tabelDatatoko;
    }

    public JTextField getjTxtnama() {
        return jTxtnama;
    }

    public void setjTxtnama(JTextField jTxtnama) {
        this.jTxtnama = jTxtnama;
    }

    public JTextField getjTxtselectednama() {
        return jTxtselectednama;
    }

    public void setjTxtselectednama(JTextField jTxtselectednama) {
        this.jTxtselectednama = jTxtselectednama;
    }

    public JComboBox<String> getjComboBoxbarang() {
        return jComboBoxbarang;
    }

    public void setjComboBoxbarang(JComboBox<String> jComboBoxbarang) {
        this.jComboBoxbarang = jComboBoxbarang;
    }

    public JComboBox<String> getjComboBoxcicilan() {
        return jComboBoxcicilan;
    }

    public void setjComboBoxcicilan(JComboBox<String> jComboBoxcicilan) {
        this.jComboBoxcicilan = jComboBoxcicilan;
    }

    

}
